name: assignment1-workflow

on:
  push:
    paths:
      - student_note.md


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print repo name
        run: echo "repository: ${{ github.repository }}"

      - name: print username
        run: echo "name: ${{ github.username }}"

